#ifndef _STAR_CPU_H_
#define _STAR_CPU_H_

/******************************************************************************
 * MODULE NAME:    star_cpu.h
 * PROJECT CODE:   Vega
 * DESCRIPTION:    
 * MAINTAINER:     Jacky
 * DATE:           15 Dec 2008
 *
 * SOURCE CONTROL: 
 *
 * LICENSE:
 *     This source code is copyright (c) 2008 Cavium Networks Inc.
 *     All rights reserved.
 *
 * REVISION HISTORY:
 *
 *
 * SOURCE:
 * ISSUES:
 * NOTES TO USERS:
 ******************************************************************************/

//#include "star_mmu_h.h"
//#include "star_sys_memory_map.h"

#define MPCORE_PRIVATE_MEM_BASE_ADDR          (SYS_MPCORE_PRIVATE_MEM_BASE_ADDR)

#define MPCORE_MEM_MAP_ADDR(reg_offset)        (MPCORE_PRIVATE_MEM_BASE_ADDR + reg_offset)
 
#define MPCORE_MEM_MAP_VALUE(reg_offset)       (*((u_int32 volatile *)MPCORE_MEM_MAP_ADDR(reg_offset)))

#define SCU_CONTROL_REG                              MPCORE_MEM_MAP_VALUE(0x0000)
#define SCU_CONFIG_REG                               MPCORE_MEM_MAP_VALUE(0x0004)
#define SCU_CPU_STATUS_REG                           MPCORE_MEM_MAP_VALUE(0x0008)
#define SCU_INVALIDATE_ALL_REG                       MPCORE_MEM_MAP_VALUE(0x000C)
#define SCU_PM_CONTROL_REG                           MPCORE_MEM_MAP_VALUE(0x0010)
#define SCU_MC_EVENTS_0_REG                          MPCORE_MEM_MAP_VALUE(0x0014)
#define SCU_MC_EVENTS_1_REG                          MPCORE_MEM_MAP_VALUE(0x0018)
#define SCU_MC_VALUE_0_REG                           MPCORE_MEM_MAP_VALUE(0x001C)
#define SCU_MC_VALUE_1_REG                           MPCORE_MEM_MAP_VALUE(0x0020)
#define SCU_MC_VALUE_2_REG                           MPCORE_MEM_MAP_VALUE(0x0024)
#define SCU_MC_VALUE_3_REG                           MPCORE_MEM_MAP_VALUE(0x0028)
#define SCU_MC_VALUE_4_REG                           MPCORE_MEM_MAP_VALUE(0x002C)
#define SCU_MC_VALUE_5_REG                           MPCORE_MEM_MAP_VALUE(0x0030)
#define SCU_MC_VALUE_6_REG                           MPCORE_MEM_MAP_VALUE(0x0034)
#define SCU_MC_VALUE_7_REG                           MPCORE_MEM_MAP_VALUE(0x0038)

//aliased address
#define CPU_INTERFACE_CONTROL_REG                    MPCORE_MEM_MAP_VALUE(0x0100)
#define CPU_INTERFACE_PRIORITY_MASK_REG              MPCORE_MEM_MAP_VALUE(0x0104)
#define CPU_INTERFACE_BIN_POINT_REG                  MPCORE_MEM_MAP_VALUE(0x0108)
#define CPU_INTERFACE_INT_ACK_REG                    MPCORE_MEM_MAP_VALUE(0x010C)
#define CPU_INTERFACE_EOI_REG                        MPCORE_MEM_MAP_VALUE(0x0110)
#define CPU_INTERFACE_RUN_PRIORITY_REG               MPCORE_MEM_MAP_VALUE(0x0114)
#define CPU_INTERFACE_HI_PENDING_INT_REG             MPCORE_MEM_MAP_VALUE(0x0118)


#define CPU_TIMER_LOAD_REG                           MPCORE_MEM_MAP_VALUE(0x0600)
#define CPU_TIMER_COUNTER_REG                        MPCORE_MEM_MAP_VALUE(0x0604)
#define CPU_TIMER_CONTROL_REG                        MPCORE_MEM_MAP_VALUE(0x0608)
#define CPU_TIMER_INTERRUPT_STATUS_REG               MPCORE_MEM_MAP_VALUE(0x060C)

#define CPU_WATCHDOG_LOAD_REG                        MPCORE_MEM_MAP_VALUE(0x0620)
#define CPU_WATCHDOG_COUNTER_REG                     MPCORE_MEM_MAP_VALUE(0x0624)
#define CPU_WATCHDOG_CONTROL_REG                     MPCORE_MEM_MAP_VALUE(0x0628)
#define CPU_WATCHDOG_INTERRUPT_STATUS_REG            MPCORE_MEM_MAP_VALUE(0x062C)
#define CPU_WATCHDOG_RESET_SENT_REG                  MPCORE_MEM_MAP_VALUE(0x0630)
#define CPU_WATCHDOG_DISABLE_REG                     MPCORE_MEM_MAP_VALUE(0x0634)

#define SCU_CONTROL_REG_ADDR                              MPCORE_MEM_MAP_ADDR(0x0000)
#define SCU_CONFIG_REG_ADDR                               MPCORE_MEM_MAP_ADDR(0x0004)
#define SCU_CPU_STATUS_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x0008)
#define SCU_INVALIDATE_ALL_REG_ADDR                       MPCORE_MEM_MAP_ADDR(0x000C)
#define SCU_PM_CONTROL_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x0010)
#define SCU_MC_EVENTS_0_REG_ADDR                          MPCORE_MEM_MAP_ADDR(0x0014)
#define SCU_MC_EVENTS_1_REG_ADDR                          MPCORE_MEM_MAP_ADDR(0x0018)
#define SCU_MC_VALUE_0_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x001C)
#define SCU_MC_VALUE_1_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x0020)
#define SCU_MC_VALUE_2_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x0024)
#define SCU_MC_VALUE_3_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x0028)
#define SCU_MC_VALUE_4_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x002C)
#define SCU_MC_VALUE_5_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x0030)
#define SCU_MC_VALUE_6_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x0034)
#define SCU_MC_VALUE_7_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x0038)

//aliased address
#define CPU_INTERFACE_CONTROL_REG_ADDR                    MPCORE_MEM_MAP_ADDR(0x0100)
#define CPU_INTERFACE_PRIORITY_MASK_REG_ADDR              MPCORE_MEM_MAP_ADDR(0x0104)
#define CPU_INTERFACE_BIN_POINT_REG_ADDR                  MPCORE_MEM_MAP_ADDR(0x0108)
#define CPU_INTERFACE_INT_ACK_REG_ADDR                    MPCORE_MEM_MAP_ADDR(0x010C)
#define CPU_INTERFACE_EOI_REG_ADDR                        MPCORE_MEM_MAP_ADDR(0x0110)
#define CPU_INTERFACE_RUN_PRIORITY_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x0114)
#define CPU_INTERFACE_HI_PENDING_INT_REG_ADDR             MPCORE_MEM_MAP_ADDR(0x0118)


#define CPU_TIMER_LOAD_REG_ADDR                           MPCORE_MEM_MAP_ADDR(0x0600)
#define CPU_TIMER_COUNTER_REG_ADDR                        MPCORE_MEM_MAP_ADDR(0x0604)
#define CPU_TIMER_CONTROL_REG_ADDR                        MPCORE_MEM_MAP_ADDR(0x0608)
#define CPU_TIMER_INTERRUPT_STATUS_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x060C)

#define CPU_WATCHDOG_LOAD_REG_ADDR                        MPCORE_MEM_MAP_ADDR(0x0620)
#define CPU_WATCHDOG_COUNTER_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0x0624)
#define CPU_WATCHDOG_CONTROL_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0x0628)
#define CPU_WATCHDOG_INTERRUPT_STATUS_REG_ADDR            MPCORE_MEM_MAP_ADDR(0x062C)
#define CPU_WATCHDOG_RESET_SENT_REG_ADDR                  MPCORE_MEM_MAP_ADDR(0x0630)
#define CPU_WATCHDOG_DISABLE_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0x0634)


/*
 *  Note that Base address of GIC is 0x1000 relative to Private memory Region:0x1F000000
 */

#define GIC_CONTROL_REG                              MPCORE_MEM_MAP_VALUE(0x1000)
#define GIC_CONTROLLER_TYPE_REG                      MPCORE_MEM_MAP_VALUE(0x1004)

#define GIC_SET_ENABLE_WORD_REG(id)                  MPCORE_MEM_MAP_VALUE(0x1100+ ((id>>5)<<2))
#define GIC_SET_ENABLE_ID0_ID31_REG                  MPCORE_MEM_MAP_VALUE(0x1100)
#define GIC_SET_ENABLE_ID32_ID63_REG                 MPCORE_MEM_MAP_VALUE(0x1104)
#define GIC_SET_ENABLE_ID64_ID95_REG                 MPCORE_MEM_MAP_VALUE(0x1108)
#define GIC_SET_ENABLE_ID96_ID127_REG                MPCORE_MEM_MAP_VALUE(0x110C)
#define GIC_SET_ENABLE_ID128_ID159_REG               MPCORE_MEM_MAP_VALUE(0x1110)
#define GIC_SET_ENABLE_ID160_ID191_REG               MPCORE_MEM_MAP_VALUE(0x1114)
#define GIC_SET_ENABLE_ID192_ID223_REG               MPCORE_MEM_MAP_VALUE(0x1118)
#define GIC_SET_ENABLE_ID224_ID255_REG               MPCORE_MEM_MAP_VALUE(0x111C)

#define GIC_CLEAR_ENABLE_WORD_REG(id)                MPCORE_MEM_MAP_VALUE(0x1180+ ((id>>5)<<2))
#define GIC_CLEAR_ENABLE_ID0_ID31_REG                MPCORE_MEM_MAP_VALUE(0x1180)
#define GIC_CLEAR_ENABLE_ID32_ID63_REG               MPCORE_MEM_MAP_VALUE(0x1184)
#define GIC_CLEAR_ENABLE_ID64_ID95_REG               MPCORE_MEM_MAP_VALUE(0x1188)
#define GIC_CLEAR_ENABLE_ID96_ID127_REG              MPCORE_MEM_MAP_VALUE(0x118C)
#define GIC_CLEAR_ENABLE_ID128_ID159_REG             MPCORE_MEM_MAP_VALUE(0x1190)
#define GIC_CLEAR_ENABLE_ID160_ID191_REG             MPCORE_MEM_MAP_VALUE(0x1194)
#define GIC_CLEAR_ENABLE_ID192_ID223_REG             MPCORE_MEM_MAP_VALUE(0x1198)
#define GIC_CLEAR_ENABLE_ID224_ID255_REG             MPCORE_MEM_MAP_VALUE(0x119C)

#define GIC_SET_PENDING_WORD_REG(id)                 MPCORE_MEM_MAP_VALUE(0x1200+ ((id>>5)<<2))
#define GIC_SET_PENDING_ID0_ID31_REG                 MPCORE_MEM_MAP_VALUE(0x1200)
#define GIC_SET_PENDING_ID32_ID63_REG                MPCORE_MEM_MAP_VALUE(0x1204)
#define GIC_SET_PENDING_ID64_ID95_REG                MPCORE_MEM_MAP_VALUE(0x1208)
#define GIC_SET_PENDING_ID96_ID127_REG               MPCORE_MEM_MAP_VALUE(0x120C)
#define GIC_SET_PENDING_ID128_ID159_REG              MPCORE_MEM_MAP_VALUE(0x1210)
#define GIC_SET_PENDING_ID160_ID191_REG              MPCORE_MEM_MAP_VALUE(0x1214)
#define GIC_SET_PENDING_ID192_ID223_REG              MPCORE_MEM_MAP_VALUE(0x1218)
#define GIC_SET_PENDING_ID224_ID255_REG              MPCORE_MEM_MAP_VALUE(0x121C)

#define GIC_CLEAR_PENDING_WORD_REG(id)               MPCORE_MEM_MAP_VALUE(0x1280+ ((id>>5)<<2))
#define GIC_CLEAR_PENDING_ID0_ID31_REG               MPCORE_MEM_MAP_VALUE(0x1280)
#define GIC_CLEAR_PENDING_ID32_ID63_REG              MPCORE_MEM_MAP_VALUE(0x1284)
#define GIC_CLEAR_PENDING_ID64_ID95_REG              MPCORE_MEM_MAP_VALUE(0x1288)
#define GIC_CLEAR_PENDING_ID96_ID127_REG             MPCORE_MEM_MAP_VALUE(0x128C)
#define GIC_CLEAR_PENDING_ID128_ID159_REG            MPCORE_MEM_MAP_VALUE(0x1290)
#define GIC_CLEAR_PENDING_ID160_ID191_REG            MPCORE_MEM_MAP_VALUE(0x1294)
#define GIC_CLEAR_PENDING_ID192_ID223_REG            MPCORE_MEM_MAP_VALUE(0x1298)
#define GIC_CLEAR_PENDING_ID224_ID255_REG            MPCORE_MEM_MAP_VALUE(0x129C)
                                                   
#define GIC_PRIORITY_WORD_REG(id)                    MPCORE_MEM_MAP_VALUE(0x1400+ ((id>>2)<<2))
#define GIC_PRIORITY_ID0_ID3_REG                     MPCORE_MEM_MAP_VALUE(0x1400)
#define GIC_PRIORITY_ID4_ID7_REG                     MPCORE_MEM_MAP_VALUE(0x1404)
#define GIC_PRIORITY_ID8_ID11_REG                    MPCORE_MEM_MAP_VALUE(0x1408)
#define GIC_PRIORITY_ID12_ID15_REG                   MPCORE_MEM_MAP_VALUE(0x140C)  
#define GIC_PRIORITY_ID16_ID19_REG                   MPCORE_MEM_MAP_VALUE(0x1410)   
#define GIC_PRIORITY_ID20_ID23_REG                   MPCORE_MEM_MAP_VALUE(0x1414)   
#define GIC_PRIORITY_ID24_ID27_REG                   MPCORE_MEM_MAP_VALUE(0x1418)   
#define GIC_PRIORITY_ID28_ID31_REG                   MPCORE_MEM_MAP_VALUE(0x141C)   
#define GIC_PRIORITY_ID32_ID35_REG                   MPCORE_MEM_MAP_VALUE(0x1420)   
#define GIC_PRIORITY_ID36_ID39_REG                   MPCORE_MEM_MAP_VALUE(0x1424)   
#define GIC_PRIORITY_ID40_ID43_REG                   MPCORE_MEM_MAP_VALUE(0x1428)   
#define GIC_PRIORITY_ID44_ID47_REG                   MPCORE_MEM_MAP_VALUE(0x142C)   
#define GIC_PRIORITY_ID48_ID51_REG                   MPCORE_MEM_MAP_VALUE(0x1430)   
#define GIC_PRIORITY_ID52_ID55_REG                   MPCORE_MEM_MAP_VALUE(0x1434)   
#define GIC_PRIORITY_ID56_ID59_REG                   MPCORE_MEM_MAP_VALUE(0x1438)   
#define GIC_PRIORITY_ID60_ID63_REG                   MPCORE_MEM_MAP_VALUE(0x143C)   
#define GIC_PRIORITY_ID64_ID67_REG                   MPCORE_MEM_MAP_VALUE(0x1440)   
#define GIC_PRIORITY_ID68_ID71_REG                   MPCORE_MEM_MAP_VALUE(0x1444)   
#define GIC_PRIORITY_ID72_ID75_REG                   MPCORE_MEM_MAP_VALUE(0x1448)   
#define GIC_PRIORITY_ID76_ID79_REG                   MPCORE_MEM_MAP_VALUE(0x144C)   
#define GIC_PRIORITY_ID80_ID83_REG                   MPCORE_MEM_MAP_VALUE(0x1450)   
#define GIC_PRIORITY_ID84_ID87_REG                   MPCORE_MEM_MAP_VALUE(0x1454)   
#define GIC_PRIORITY_ID88_ID91_REG                   MPCORE_MEM_MAP_VALUE(0x1458)   
#define GIC_PRIORITY_ID92_ID95_REG                   MPCORE_MEM_MAP_VALUE(0x145C)   
#define GIC_PRIORITY_ID96_ID99_REG                   MPCORE_MEM_MAP_VALUE(0x1460) 
#define GIC_PRIORITY_ID100_ID103_REG                 MPCORE_MEM_MAP_VALUE(0x1464) 
#define GIC_PRIORITY_ID104_ID107_REG                 MPCORE_MEM_MAP_VALUE(0x1468) 
#define GIC_PRIORITY_ID108_ID111_REG                 MPCORE_MEM_MAP_VALUE(0x146C) 
#define GIC_PRIORITY_ID112_ID115_REG                 MPCORE_MEM_MAP_VALUE(0x1470) 
#define GIC_PRIORITY_ID116_ID119_REG                 MPCORE_MEM_MAP_VALUE(0x1474) 
#define GIC_PRIORITY_ID120_ID123_REG                 MPCORE_MEM_MAP_VALUE(0x1478) 
#define GIC_PRIORITY_ID124_ID127_REG                 MPCORE_MEM_MAP_VALUE(0x147C) 
#define GIC_PRIORITY_ID128_ID131_REG                 MPCORE_MEM_MAP_VALUE(0x1480) 
#define GIC_PRIORITY_ID132_ID135_REG                 MPCORE_MEM_MAP_VALUE(0x1484) 
#define GIC_PRIORITY_ID136_ID139_REG                 MPCORE_MEM_MAP_VALUE(0x1488) 
#define GIC_PRIORITY_ID140_ID143_REG                 MPCORE_MEM_MAP_VALUE(0x148C) 
#define GIC_PRIORITY_ID144_ID147_REG                 MPCORE_MEM_MAP_VALUE(0x1490) 
#define GIC_PRIORITY_ID148_ID151_REG                 MPCORE_MEM_MAP_VALUE(0x1494) 
#define GIC_PRIORITY_ID152_ID155_REG                 MPCORE_MEM_MAP_VALUE(0x1498) 
#define GIC_PRIORITY_ID156_ID159_REG                 MPCORE_MEM_MAP_VALUE(0x149C) 
#define GIC_PRIORITY_ID160_ID163_REG                 MPCORE_MEM_MAP_VALUE(0x14A0) 
#define GIC_PRIORITY_ID164_ID167_REG                 MPCORE_MEM_MAP_VALUE(0x14A4) 
#define GIC_PRIORITY_ID168_ID171_REG                 MPCORE_MEM_MAP_VALUE(0x14A8) 
#define GIC_PRIORITY_ID172_ID175_REG                 MPCORE_MEM_MAP_VALUE(0x14AC) 
#define GIC_PRIORITY_ID176_ID179_REG                 MPCORE_MEM_MAP_VALUE(0x14B0) 
#define GIC_PRIORITY_ID180_ID183_REG                 MPCORE_MEM_MAP_VALUE(0x14B4) 
#define GIC_PRIORITY_ID184_ID187_REG                 MPCORE_MEM_MAP_VALUE(0x14B8) 
#define GIC_PRIORITY_ID188_ID191_REG                 MPCORE_MEM_MAP_VALUE(0x14BC) 
#define GIC_PRIORITY_ID192_ID195_REG                 MPCORE_MEM_MAP_VALUE(0x14C0) 
#define GIC_PRIORITY_ID196_ID199_REG                 MPCORE_MEM_MAP_VALUE(0x14C4) 
#define GIC_PRIORITY_ID200_ID203_REG                 MPCORE_MEM_MAP_VALUE(0x14C8) 
#define GIC_PRIORITY_ID204_ID207_REG                 MPCORE_MEM_MAP_VALUE(0x14CC) 
#define GIC_PRIORITY_ID208_ID211_REG                 MPCORE_MEM_MAP_VALUE(0x14D0) 
#define GIC_PRIORITY_ID212_ID215_REG                 MPCORE_MEM_MAP_VALUE(0x14D4) 
#define GIC_PRIORITY_ID216_ID219_REG                 MPCORE_MEM_MAP_VALUE(0x14D8) 
#define GIC_PRIORITY_ID220_ID223_REG                 MPCORE_MEM_MAP_VALUE(0x14DC) 
#define GIC_PRIORITY_ID224_ID227_REG                 MPCORE_MEM_MAP_VALUE(0x14E0) 
#define GIC_PRIORITY_ID228_ID231_REG                 MPCORE_MEM_MAP_VALUE(0x14E4) 
#define GIC_PRIORITY_ID232_ID235_REG                 MPCORE_MEM_MAP_VALUE(0x14E8) 
#define GIC_PRIORITY_ID236_ID239_REG                 MPCORE_MEM_MAP_VALUE(0x14EC) 
#define GIC_PRIORITY_ID240_ID243_REG                 MPCORE_MEM_MAP_VALUE(0x14F0) 
#define GIC_PRIORITY_ID244_ID247_REG                 MPCORE_MEM_MAP_VALUE(0x14F4) 
#define GIC_PRIORITY_ID248_ID251_REG                 MPCORE_MEM_MAP_VALUE(0x14F8) 
#define GIC_PRIORITY_ID252_ID255_REG                 MPCORE_MEM_MAP_VALUE(0x14FC) 

#define GIC_CPU_TARGET_WORD_REG(id)                  MPCORE_MEM_MAP_VALUE(0x1800+ ((id>>2)<<2))
#define GIC_CPU_TARGET_ID0_ID3_REG                   MPCORE_MEM_MAP_VALUE(0X1800)
#define GIC_CPU_TARGET_ID4_ID7_REG                   MPCORE_MEM_MAP_VALUE(0X1804)
#define GIC_CPU_TARGET_ID8_ID11_REG                  MPCORE_MEM_MAP_VALUE(0X1808)
#define GIC_CPU_TARGET_ID12_ID15_REG                 MPCORE_MEM_MAP_VALUE(0X180C)  
#define GIC_CPU_TARGET_ID16_ID19_REG                 MPCORE_MEM_MAP_VALUE(0X1810)   
#define GIC_CPU_TARGET_ID20_ID23_REG                 MPCORE_MEM_MAP_VALUE(0X1814)   
#define GIC_CPU_TARGET_ID24_ID27_REG                 MPCORE_MEM_MAP_VALUE(0X1818)   
#define GIC_CPU_TARGET_ID28_ID31_REG                 MPCORE_MEM_MAP_VALUE(0X181C)   
#define GIC_CPU_TARGET_ID32_ID35_REG                 MPCORE_MEM_MAP_VALUE(0X1820)   
#define GIC_CPU_TARGET_ID36_ID39_REG                 MPCORE_MEM_MAP_VALUE(0X1824)   
#define GIC_CPU_TARGET_ID40_ID43_REG                 MPCORE_MEM_MAP_VALUE(0X1828)   
#define GIC_CPU_TARGET_ID44_ID47_REG                 MPCORE_MEM_MAP_VALUE(0X182C)   
#define GIC_CPU_TARGET_ID48_ID51_REG                 MPCORE_MEM_MAP_VALUE(0X1830)   
#define GIC_CPU_TARGET_ID52_ID55_REG                 MPCORE_MEM_MAP_VALUE(0X1834)   
#define GIC_CPU_TARGET_ID56_ID59_REG                 MPCORE_MEM_MAP_VALUE(0X1838)   
#define GIC_CPU_TARGET_ID60_ID63_REG                 MPCORE_MEM_MAP_VALUE(0X183C)   
#define GIC_CPU_TARGET_ID64_ID67_REG                 MPCORE_MEM_MAP_VALUE(0X1840)   
#define GIC_CPU_TARGET_ID68_ID71_REG                 MPCORE_MEM_MAP_VALUE(0X1844)   
#define GIC_CPU_TARGET_ID72_ID75_REG                 MPCORE_MEM_MAP_VALUE(0X1848)   
#define GIC_CPU_TARGET_ID76_ID79_REG                 MPCORE_MEM_MAP_VALUE(0X184C)   
#define GIC_CPU_TARGET_ID80_ID83_REG                 MPCORE_MEM_MAP_VALUE(0X1850)   
#define GIC_CPU_TARGET_ID84_ID87_REG                 MPCORE_MEM_MAP_VALUE(0X1854)   
#define GIC_CPU_TARGET_ID88_ID91_REG                 MPCORE_MEM_MAP_VALUE(0X1858)   
#define GIC_CPU_TARGET_ID92_ID95_REG                 MPCORE_MEM_MAP_VALUE(0X185C)   
#define GIC_CPU_TARGET_ID96_ID99_REG                 MPCORE_MEM_MAP_VALUE(0X1860) 
#define GIC_CPU_TARGET_ID100_ID103_REG               MPCORE_MEM_MAP_VALUE(0X1864) 
#define GIC_CPU_TARGET_ID104_ID107_REG               MPCORE_MEM_MAP_VALUE(0X1868) 
#define GIC_CPU_TARGET_ID108_ID111_REG               MPCORE_MEM_MAP_VALUE(0X186C) 
#define GIC_CPU_TARGET_ID112_ID115_REG               MPCORE_MEM_MAP_VALUE(0X1870) 
#define GIC_CPU_TARGET_ID116_ID119_REG               MPCORE_MEM_MAP_VALUE(0X1874) 
#define GIC_CPU_TARGET_ID120_ID123_REG               MPCORE_MEM_MAP_VALUE(0X1878) 
#define GIC_CPU_TARGET_ID124_ID127_REG               MPCORE_MEM_MAP_VALUE(0X187C) 
#define GIC_CPU_TARGET_ID128_ID131_REG               MPCORE_MEM_MAP_VALUE(0X1880) 
#define GIC_CPU_TARGET_ID132_ID135_REG               MPCORE_MEM_MAP_VALUE(0X1884) 
#define GIC_CPU_TARGET_ID136_ID139_REG               MPCORE_MEM_MAP_VALUE(0X1888) 
#define GIC_CPU_TARGET_ID140_ID143_REG               MPCORE_MEM_MAP_VALUE(0X188C) 
#define GIC_CPU_TARGET_ID144_ID147_REG               MPCORE_MEM_MAP_VALUE(0X1890) 
#define GIC_CPU_TARGET_ID148_ID151_REG               MPCORE_MEM_MAP_VALUE(0X1894) 
#define GIC_CPU_TARGET_ID152_ID155_REG               MPCORE_MEM_MAP_VALUE(0X1898) 
#define GIC_CPU_TARGET_ID156_ID159_REG               MPCORE_MEM_MAP_VALUE(0X189C) 
#define GIC_CPU_TARGET_ID160_ID163_REG               MPCORE_MEM_MAP_VALUE(0X18A0) 
#define GIC_CPU_TARGET_ID164_ID167_REG               MPCORE_MEM_MAP_VALUE(0X18A4) 
#define GIC_CPU_TARGET_ID168_ID171_REG               MPCORE_MEM_MAP_VALUE(0X18A8) 
#define GIC_CPU_TARGET_ID172_ID175_REG               MPCORE_MEM_MAP_VALUE(0X18AC) 
#define GIC_CPU_TARGET_ID176_ID179_REG               MPCORE_MEM_MAP_VALUE(0X18B0) 
#define GIC_CPU_TARGET_ID180_ID183_REG               MPCORE_MEM_MAP_VALUE(0X18B4) 
#define GIC_CPU_TARGET_ID184_ID187_REG               MPCORE_MEM_MAP_VALUE(0X18B8) 
#define GIC_CPU_TARGET_ID188_ID191_REG               MPCORE_MEM_MAP_VALUE(0X18BC) 
#define GIC_CPU_TARGET_ID192_ID195_REG               MPCORE_MEM_MAP_VALUE(0X18C0) 
#define GIC_CPU_TARGET_ID196_ID199_REG               MPCORE_MEM_MAP_VALUE(0X18C4) 
#define GIC_CPU_TARGET_ID200_ID203_REG               MPCORE_MEM_MAP_VALUE(0X18C8) 
#define GIC_CPU_TARGET_ID204_ID207_REG               MPCORE_MEM_MAP_VALUE(0X18CC) 
#define GIC_CPU_TARGET_ID208_ID211_REG               MPCORE_MEM_MAP_VALUE(0X18D0) 
#define GIC_CPU_TARGET_ID212_ID215_REG               MPCORE_MEM_MAP_VALUE(0X18D4) 
#define GIC_CPU_TARGET_ID216_ID219_REG               MPCORE_MEM_MAP_VALUE(0X18D8) 
#define GIC_CPU_TARGET_ID220_ID223_REG               MPCORE_MEM_MAP_VALUE(0X18DC) 
#define GIC_CPU_TARGET_ID224_ID227_REG               MPCORE_MEM_MAP_VALUE(0X18E0) 
#define GIC_CPU_TARGET_ID228_ID231_REG               MPCORE_MEM_MAP_VALUE(0X18E4) 
#define GIC_CPU_TARGET_ID232_ID235_REG               MPCORE_MEM_MAP_VALUE(0X18E8) 
#define GIC_CPU_TARGET_ID236_ID239_REG               MPCORE_MEM_MAP_VALUE(0X18EC) 
#define GIC_CPU_TARGET_ID240_ID243_REG               MPCORE_MEM_MAP_VALUE(0X18F0) 
#define GIC_CPU_TARGET_ID244_ID247_REG               MPCORE_MEM_MAP_VALUE(0X18F4) 
#define GIC_CPU_TARGET_ID248_ID251_REG               MPCORE_MEM_MAP_VALUE(0X18F8) 
#define GIC_CPU_TARGET_ID252_ID255_REG               MPCORE_MEM_MAP_VALUE(0X18FC) 

#define GIC_CONFIG_WORD_REG(id)                      MPCORE_MEM_MAP_VALUE(0x1C00+ ((id>>4)<<2))
#define GIC_CONFIG_ID0_ID15_REG                      MPCORE_MEM_MAP_VALUE(0X1C00)
#define GIC_CONFIG_ID16_ID31_REG                     MPCORE_MEM_MAP_VALUE(0X1C04)
#define GIC_CONFIG_ID32_ID47_REG                     MPCORE_MEM_MAP_VALUE(0X1C08)
#define GIC_CONFIG_ID48_ID64_REG                     MPCORE_MEM_MAP_VALUE(0X1C0C)  
#define GIC_CONFIG_ID64_ID79_REG                     MPCORE_MEM_MAP_VALUE(0X1C10)   
#define GIC_CONFIG_ID80_ID95_REG                     MPCORE_MEM_MAP_VALUE(0X1C14)   
#define GIC_CONFIG_ID96_ID111_REG                    MPCORE_MEM_MAP_VALUE(0x1C18)   
#define GIC_CONFIG_ID112_ID127_REG                   MPCORE_MEM_MAP_VALUE(0x1C1C)   
#define GIC_CONFIG_ID128_ID143_REG                   MPCORE_MEM_MAP_VALUE(0x1C20)   
#define GIC_CONFIG_ID144_ID159_REG                   MPCORE_MEM_MAP_VALUE(0x1C24)   
#define GIC_CONFIG_ID160_ID175_REG                   MPCORE_MEM_MAP_VALUE(0x1C28)   
#define GIC_CONFIG_ID176_ID191_REG                   MPCORE_MEM_MAP_VALUE(0x1C2C)   
#define GIC_CONFIG_ID192_ID207_REG                   MPCORE_MEM_MAP_VALUE(0x1C30)   
#define GIC_CONFIG_ID208_ID223_REG                   MPCORE_MEM_MAP_VALUE(0x1C34)   
#define GIC_CONFIG_ID224_ID239_REG                   MPCORE_MEM_MAP_VALUE(0x1C38)   
#define GIC_CONFIG_ID240_ID255_REG                   MPCORE_MEM_MAP_VALUE(0x1C3C)   

#define GIC_INT_LINE_LEVEL_WORD_REG(id)              MPCORE_MEM_MAP_VALUE(0x1D00+ ((id>>5)<<2))
#define GIC_INT_LINE_LEVEL_ID0_ID31_REG              MPCORE_MEM_MAP_VALUE(0x1D00)
#define GIC_INT_LINE_LEVEL_ID32_ID63_REG             MPCORE_MEM_MAP_VALUE(0x1D04)
#define GIC_INT_LINE_LEVEL_ID64_ID95_REG             MPCORE_MEM_MAP_VALUE(0x1D08)
#define GIC_INT_LINE_LEVEL_ID96_ID127_REG            MPCORE_MEM_MAP_VALUE(0x1D0C)
#define GIC_INT_LINE_LEVEL_ID128_ID159_REG           MPCORE_MEM_MAP_VALUE(0x1D10)
#define GIC_INT_LINE_LEVEL_ID160_ID191_REG           MPCORE_MEM_MAP_VALUE(0x1D14)
#define GIC_INT_LINE_LEVEL_ID192_ID223_REG           MPCORE_MEM_MAP_VALUE(0x1D18)
#define GIC_INT_LINE_LEVEL_ID224_ID255_REG           MPCORE_MEM_MAP_VALUE(0x1D1C)
                                                    
#define GIC_SOFT_INTERRUPT_REG                       MPCORE_MEM_MAP_VALUE(0x1F00)   



//...........
#define GIC_CONTROL_REG_ADDR                              MPCORE_MEM_MAP_ADDR(0x1000)
#define GIC_CONTROLLER_TYPE_REG_ADDR                      MPCORE_MEM_MAP_ADDR(0x1004)

#define GIC_SET_ENABLE_WORD_REG_ADDR(id)                  MPCORE_MEM_MAP_ADDR(0x1100+ ((id>>5)<<2))
#define GIC_SET_ENABLE_ID0_ID31_REG_ADDR                  MPCORE_MEM_MAP_ADDR(0x1100)
#define GIC_SET_ENABLE_ID32_ID63_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1104)
#define GIC_SET_ENABLE_ID64_ID95_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1108)
#define GIC_SET_ENABLE_ID96_ID127_REG_ADDR                MPCORE_MEM_MAP_ADDR(0x110C)
#define GIC_SET_ENABLE_ID128_ID159_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x1110)
#define GIC_SET_ENABLE_ID160_ID191_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x1114)
#define GIC_SET_ENABLE_ID192_ID223_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x1118)
#define GIC_SET_ENABLE_ID224_ID255_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x111C)

#define GIC_CLEAR_ENABLE_WORD_REG_ADDR(id)                MPCORE_MEM_MAP_ADDR(0x1180+ ((id>>5)<<2))
#define GIC_CLEAR_ENABLE_ID0_ID31_REG_ADDR                MPCORE_MEM_MAP_ADDR(0x1180)
#define GIC_CLEAR_ENABLE_ID32_ID63_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x1184)
#define GIC_CLEAR_ENABLE_ID64_ID95_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x1188)
#define GIC_CLEAR_ENABLE_ID96_ID127_REG_ADDR              MPCORE_MEM_MAP_ADDR(0x118C)
#define GIC_CLEAR_ENABLE_ID128_ID159_REG_ADDR             MPCORE_MEM_MAP_ADDR(0x1190)
#define GIC_CLEAR_ENABLE_ID160_ID191_REG_ADDR             MPCORE_MEM_MAP_ADDR(0x1194)
#define GIC_CLEAR_ENABLE_ID192_ID223_REG_ADDR             MPCORE_MEM_MAP_ADDR(0x1198)
#define GIC_CLEAR_ENABLE_ID224_ID255_REG_ADDR             MPCORE_MEM_MAP_ADDR(0x119C)

#define GIC_SET_PENDING_WORD_REG_ADDR(id)                 MPCORE_MEM_MAP_ADDR(0x1200+ ((id>>5)<<2))
#define GIC_SET_PENDING_ID0_ID31_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1200)
#define GIC_SET_PENDING_ID32_ID63_REG_ADDR                MPCORE_MEM_MAP_ADDR(0x1204)
#define GIC_SET_PENDING_ID64_ID95_REG_ADDR                MPCORE_MEM_MAP_ADDR(0x1208)
#define GIC_SET_PENDING_ID96_ID127_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x120C)
#define GIC_SET_PENDING_ID128_ID159_REG_ADDR              MPCORE_MEM_MAP_ADDR(0x1210)
#define GIC_SET_PENDING_ID160_ID191_REG_ADDR              MPCORE_MEM_MAP_ADDR(0x1214)
#define GIC_SET_PENDING_ID192_ID223_REG_ADDR              MPCORE_MEM_MAP_ADDR(0x1218)
#define GIC_SET_PENDING_ID224_ID255_REG_ADDR              MPCORE_MEM_MAP_ADDR(0x121C)

#define GIC_CLEAR_PENDING_WORD_REG_ADDR(id)               MPCORE_MEM_MAP_ADDR(0x1280+ ((id>>5)<<2))
#define GIC_CLEAR_PENDING_ID0_ID31_REG_ADDR               MPCORE_MEM_MAP_ADDR(0x1280)
#define GIC_CLEAR_PENDING_ID32_ID63_REG_ADDR              MPCORE_MEM_MAP_ADDR(0x1284)
#define GIC_CLEAR_PENDING_ID64_ID95_REG_ADDR              MPCORE_MEM_MAP_ADDR(0x1288)
#define GIC_CLEAR_PENDING_ID96_ID127_REG_ADDR             MPCORE_MEM_MAP_ADDR(0x128C)
#define GIC_CLEAR_PENDING_ID128_ID159_REG_ADDR            MPCORE_MEM_MAP_ADDR(0x1290)
#define GIC_CLEAR_PENDING_ID160_ID191_REG_ADDR            MPCORE_MEM_MAP_ADDR(0x1294)
#define GIC_CLEAR_PENDING_ID192_ID223_REG_ADDR            MPCORE_MEM_MAP_ADDR(0x1298)
#define GIC_CLEAR_PENDING_ID224_ID255_REG_ADDR            MPCORE_MEM_MAP_ADDR(0x129C)
                                                   
#define GIC_PRIORITY_WORD_REG_ADDR(id)                    MPCORE_MEM_MAP_ADDR(0x1400+ ((id>>2)<<2))
#define GIC_PRIORITY_ID0_ID3_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0x1400)
#define GIC_PRIORITY_ID4_ID7_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0x1404)
#define GIC_PRIORITY_ID8_ID11_REG_ADDR                    MPCORE_MEM_MAP_ADDR(0x1408)
#define GIC_PRIORITY_ID12_ID15_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x140C)  
#define GIC_PRIORITY_ID16_ID19_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1410)   
#define GIC_PRIORITY_ID20_ID23_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1414)   
#define GIC_PRIORITY_ID24_ID27_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1418)   
#define GIC_PRIORITY_ID28_ID31_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x141C)   
#define GIC_PRIORITY_ID32_ID35_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1420)   
#define GIC_PRIORITY_ID36_ID39_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1424)   
#define GIC_PRIORITY_ID40_ID43_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1428)   
#define GIC_PRIORITY_ID44_ID47_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x142C)   
#define GIC_PRIORITY_ID48_ID51_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1430)   
#define GIC_PRIORITY_ID52_ID55_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1434)   
#define GIC_PRIORITY_ID56_ID59_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1438)   
#define GIC_PRIORITY_ID60_ID63_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x143C)   
#define GIC_PRIORITY_ID64_ID67_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1440)   
#define GIC_PRIORITY_ID68_ID71_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1444)   
#define GIC_PRIORITY_ID72_ID75_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1448)   
#define GIC_PRIORITY_ID76_ID79_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x144C)   
#define GIC_PRIORITY_ID80_ID83_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1450)   
#define GIC_PRIORITY_ID84_ID87_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1454)   
#define GIC_PRIORITY_ID88_ID91_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1458)   
#define GIC_PRIORITY_ID92_ID95_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x145C)   
#define GIC_PRIORITY_ID96_ID99_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1460) 
#define GIC_PRIORITY_ID100_ID103_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1464) 
#define GIC_PRIORITY_ID104_ID107_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1468) 
#define GIC_PRIORITY_ID108_ID111_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x146C) 
#define GIC_PRIORITY_ID112_ID115_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1470) 
#define GIC_PRIORITY_ID116_ID119_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1474) 
#define GIC_PRIORITY_ID120_ID123_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1478) 
#define GIC_PRIORITY_ID124_ID127_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x147C) 
#define GIC_PRIORITY_ID128_ID131_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1480) 
#define GIC_PRIORITY_ID132_ID135_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1484) 
#define GIC_PRIORITY_ID136_ID139_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1488) 
#define GIC_PRIORITY_ID140_ID143_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x148C) 
#define GIC_PRIORITY_ID144_ID147_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1490) 
#define GIC_PRIORITY_ID148_ID151_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1494) 
#define GIC_PRIORITY_ID152_ID155_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x1498) 
#define GIC_PRIORITY_ID156_ID159_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x149C) 
#define GIC_PRIORITY_ID160_ID163_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14A0) 
#define GIC_PRIORITY_ID164_ID167_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14A4) 
#define GIC_PRIORITY_ID168_ID171_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14A8) 
#define GIC_PRIORITY_ID172_ID175_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14AC) 
#define GIC_PRIORITY_ID176_ID179_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14B0) 
#define GIC_PRIORITY_ID180_ID183_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14B4) 
#define GIC_PRIORITY_ID184_ID187_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14B8) 
#define GIC_PRIORITY_ID188_ID191_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14BC) 
#define GIC_PRIORITY_ID192_ID195_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14C0) 
#define GIC_PRIORITY_ID196_ID199_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14C4) 
#define GIC_PRIORITY_ID200_ID203_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14C8) 
#define GIC_PRIORITY_ID204_ID207_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14CC) 
#define GIC_PRIORITY_ID208_ID211_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14D0) 
#define GIC_PRIORITY_ID212_ID215_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14D4) 
#define GIC_PRIORITY_ID216_ID219_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14D8) 
#define GIC_PRIORITY_ID220_ID223_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14DC) 
#define GIC_PRIORITY_ID224_ID227_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14E0) 
#define GIC_PRIORITY_ID228_ID231_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14E4) 
#define GIC_PRIORITY_ID232_ID235_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14E8) 
#define GIC_PRIORITY_ID236_ID239_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14EC) 
#define GIC_PRIORITY_ID240_ID243_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14F0) 
#define GIC_PRIORITY_ID244_ID247_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14F4) 
#define GIC_PRIORITY_ID248_ID251_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14F8) 
#define GIC_PRIORITY_ID252_ID255_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0x14FC) 

#define GIC_CPU_TARGET_WORD_REG_ADDR(id)                  MPCORE_MEM_MAP_ADDR(0x1800+ ((id>>2)<<2))
#define GIC_CPU_TARGET_ID0_ID3_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0X1800)
#define GIC_CPU_TARGET_ID4_ID7_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0X1804)
#define GIC_CPU_TARGET_ID8_ID11_REG_ADDR                  MPCORE_MEM_MAP_ADDR(0X1808)
#define GIC_CPU_TARGET_ID12_ID15_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X180C)  
#define GIC_CPU_TARGET_ID16_ID19_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1810)   
#define GIC_CPU_TARGET_ID20_ID23_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1814)   
#define GIC_CPU_TARGET_ID24_ID27_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1818)   
#define GIC_CPU_TARGET_ID28_ID31_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X181C)   
#define GIC_CPU_TARGET_ID32_ID35_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1820)   
#define GIC_CPU_TARGET_ID36_ID39_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1824)   
#define GIC_CPU_TARGET_ID40_ID43_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1828)   
#define GIC_CPU_TARGET_ID44_ID47_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X182C)   
#define GIC_CPU_TARGET_ID48_ID51_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1830)   
#define GIC_CPU_TARGET_ID52_ID55_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1834)   
#define GIC_CPU_TARGET_ID56_ID59_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1838)   
#define GIC_CPU_TARGET_ID60_ID63_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X183C)   
#define GIC_CPU_TARGET_ID64_ID67_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1840)   
#define GIC_CPU_TARGET_ID68_ID71_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1844)   
#define GIC_CPU_TARGET_ID72_ID75_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1848)   
#define GIC_CPU_TARGET_ID76_ID79_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X184C)   
#define GIC_CPU_TARGET_ID80_ID83_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1850)   
#define GIC_CPU_TARGET_ID84_ID87_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1854)   
#define GIC_CPU_TARGET_ID88_ID91_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1858)   
#define GIC_CPU_TARGET_ID92_ID95_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X185C)   
#define GIC_CPU_TARGET_ID96_ID99_REG_ADDR                 MPCORE_MEM_MAP_ADDR(0X1860) 
#define GIC_CPU_TARGET_ID100_ID103_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1864) 
#define GIC_CPU_TARGET_ID104_ID107_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1868) 
#define GIC_CPU_TARGET_ID108_ID111_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X186C) 
#define GIC_CPU_TARGET_ID112_ID115_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1870) 
#define GIC_CPU_TARGET_ID116_ID119_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1874) 
#define GIC_CPU_TARGET_ID120_ID123_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1878) 
#define GIC_CPU_TARGET_ID124_ID127_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X187C) 
#define GIC_CPU_TARGET_ID128_ID131_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1880) 
#define GIC_CPU_TARGET_ID132_ID135_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1884) 
#define GIC_CPU_TARGET_ID136_ID139_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1888) 
#define GIC_CPU_TARGET_ID140_ID143_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X188C) 
#define GIC_CPU_TARGET_ID144_ID147_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1890) 
#define GIC_CPU_TARGET_ID148_ID151_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1894) 
#define GIC_CPU_TARGET_ID152_ID155_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X1898) 
#define GIC_CPU_TARGET_ID156_ID159_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X189C) 
#define GIC_CPU_TARGET_ID160_ID163_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18A0) 
#define GIC_CPU_TARGET_ID164_ID167_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18A4) 
#define GIC_CPU_TARGET_ID168_ID171_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18A8) 
#define GIC_CPU_TARGET_ID172_ID175_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18AC) 
#define GIC_CPU_TARGET_ID176_ID179_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18B0) 
#define GIC_CPU_TARGET_ID180_ID183_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18B4) 
#define GIC_CPU_TARGET_ID184_ID187_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18B8) 
#define GIC_CPU_TARGET_ID188_ID191_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18BC) 
#define GIC_CPU_TARGET_ID192_ID195_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18C0) 
#define GIC_CPU_TARGET_ID196_ID199_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18C4) 
#define GIC_CPU_TARGET_ID200_ID203_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18C8) 
#define GIC_CPU_TARGET_ID204_ID207_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18CC) 
#define GIC_CPU_TARGET_ID208_ID211_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18D0) 
#define GIC_CPU_TARGET_ID212_ID215_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18D4) 
#define GIC_CPU_TARGET_ID216_ID219_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18D8) 
#define GIC_CPU_TARGET_ID220_ID223_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18DC) 
#define GIC_CPU_TARGET_ID224_ID227_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18E0) 
#define GIC_CPU_TARGET_ID228_ID231_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18E4) 
#define GIC_CPU_TARGET_ID232_ID235_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18E8) 
#define GIC_CPU_TARGET_ID236_ID239_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18EC) 
#define GIC_CPU_TARGET_ID240_ID243_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18F0) 
#define GIC_CPU_TARGET_ID244_ID247_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18F4) 
#define GIC_CPU_TARGET_ID248_ID251_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18F8) 
#define GIC_CPU_TARGET_ID252_ID255_REG_ADDR               MPCORE_MEM_MAP_ADDR(0X18FC) 

#define GIC_CONFIG_WORD_REG_ADDR(id)                      MPCORE_MEM_MAP_ADDR(0x1C00+ ((id>>4)<<2))
#define GIC_CONFIG_ID0_ID15_REG_ADDR                      MPCORE_MEM_MAP_ADDR(0X1C00)
#define GIC_CONFIG_ID16_ID31_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0X1C04)
#define GIC_CONFIG_ID32_ID47_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0X1C08)
#define GIC_CONFIG_ID48_ID64_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0X1C0C)  
#define GIC_CONFIG_ID64_ID79_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0X1C10)   
#define GIC_CONFIG_ID80_ID95_REG_ADDR                     MPCORE_MEM_MAP_ADDR(0X1C14)   
#define GIC_CONFIG_ID96_ID111_REG_ADDR                    MPCORE_MEM_MAP_ADDR(0x1C18)   
#define GIC_CONFIG_ID112_ID127_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1C1C)   
#define GIC_CONFIG_ID128_ID143_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1C20)   
#define GIC_CONFIG_ID144_ID159_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1C24)   
#define GIC_CONFIG_ID160_ID175_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1C28)   
#define GIC_CONFIG_ID176_ID191_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1C2C)   
#define GIC_CONFIG_ID192_ID207_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1C30)   
#define GIC_CONFIG_ID208_ID223_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1C34)   
#define GIC_CONFIG_ID224_ID239_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1C38)   
#define GIC_CONFIG_ID240_ID255_REG_ADDR                   MPCORE_MEM_MAP_ADDR(0x1C3C)   

#define GIC_INT_LINE_LEVEL_WORD_REG_ADDR(id)              MPCORE_MEM_MAP_ADDR(0x1D00+ ((id>>5)<<2))
#define GIC_INT_LINE_LEVEL_ID0_ID31_REG_ADDR              MPCORE_MEM_MAP_ADDR(0x1D00)
#define GIC_INT_LINE_LEVEL_ID32_ID63_REG_ADDR             MPCORE_MEM_MAP_ADDR(0x1D04)
#define GIC_INT_LINE_LEVEL_ID64_ID95_REG_ADDR             MPCORE_MEM_MAP_ADDR(0x1D08)
#define GIC_INT_LINE_LEVEL_ID96_ID127_REG_ADDR            MPCORE_MEM_MAP_ADDR(0x1D0C)
#define GIC_INT_LINE_LEVEL_ID128_ID159_REG_ADDR           MPCORE_MEM_MAP_ADDR(0x1D10)
#define GIC_INT_LINE_LEVEL_ID160_ID191_REG_ADDR           MPCORE_MEM_MAP_ADDR(0x1D14)
#define GIC_INT_LINE_LEVEL_ID192_ID223_REG_ADDR           MPCORE_MEM_MAP_ADDR(0x1D18)
#define GIC_INT_LINE_LEVEL_ID224_ID255_REG_ADDR           MPCORE_MEM_MAP_ADDR(0x1D1C)
                                                    
#define GIC_SOFT_INTERRUPT_REG_ADDR                       MPCORE_MEM_MAP_ADDR(0x1F00)   

//..........
/* 
 * Bit definitions for the control register
 */
#define EnableMMU                       0x0001
#define EnableAlignFault                0x0002
#define EnableDcache                    0x0004
//#define EnableWB                        0x0008
//#define EnableBigEndian                 0x0080
#define EnableMMU_S                     0x0100        /* selects MMU access checks */
#define EnableMMU_R                     0x0200        /* selects MMU access checks */
#define EnableIcache                    0x1000

#define BranchPrediction                0x0800
#define EnableHighVectors               0x2000        /* Vectors relocated to 0xFFFF0000 */


/*


*/


/*  
 * Definitions used in conditional assembly of Icache, Dcache and Write Buffer
 * options
 */
#define IC_ON                           EnableIcache
#define IC_OFF                          0x0

#define DC_ON                           EnableDcache
#define DC_OFF                          0x0

//#define BIGENDIAN_ON                    EnableBigEndian
//#define BIGENDIAN_OFF                   0x0


#define CACHE_WAY_0                     (0)
#define CACHE_WAY_1                     (1)
#define CACHE_WAY_2                     (2)
#define CACHE_WAY_3                     (3)


/*
 *  Function Declaration
 */
int     Hal_Cpu_Read_MMU_Configuration(void);
void    Hal_Cpu_Write_MMU_Configuration(int);

int     Hal_Cpu_Read_Domain_Access_Control(void);
void    Hal_Cpu_Write_Domain_Access_Control(int);

void    Hal_Cpu_Enable_ICache(void);
void    Hal_Cpu_Disable_ICache(void);
void    Hal_Cpu_Invalidate_ICache_All(void);
void    Hal_Cpu_Invalidate_ICache_Entry(int);
void    Hal_Cpu_Prefetch_ICache_Entry(int);
//void    Hal_Cpu_Lockdown_ICache_Entry(u_int32, u_int32);
//void    Hal_Cpu_Disable_ICache_Lockdown(u_int32);

void    Hal_Cpu_Enable_DCache(void);
void    Hal_Cpu_Disable_DCache(void);
void    Hal_Cpu_Invalidate_DCache_All(void);
void    Hal_Cpu_Invalidate_DCache_Entry(int);
void    Hal_Cpu_Invalidate_DCache_Range(int, int);
void    Hal_Cpu_Clean_DCache_All(void);
void    Hal_Cpu_Clean_DCache_Entry(int);
void    Hal_Cpu_Clean_DCache_Range(int, int);
void    Hal_Cpu_Clean_Invalidate_DCache_All(void);
void    Hal_Cpu_Clean_Invalidate_DCache_Entry(int);
void    Hal_Cpu_Clean_Invalidate_DCache_Range(int, int);

int     Hal_Cpu_Lockdown_DCache_Way(u_int32);
int     Hal_Cpu_Unlock_DCache_Way(u_int32);

void    Hal_Cpu_Lockdown_DCache_Entry(u_int32, u_int32);
void    Hal_Cpu_Disable_DCache_Lockdown(u_int32);


void    Hal_Cpu_Invalidate_ICache_DCache_All(void);

void    Hal_Cpu_Drain_Write_Buffer(void);

void    Hal_Cpu_Invalidate_UTLB_All(void);
void    Hal_Cpu_Invalidate_UTLB_Entry(int);
void    Hal_Cpu_Invalidate_ITLB_All(void);
void    Hal_Cpu_Invalidate_ITLB_Entry(int);
void    Hal_Cpu_Invalidate_DTLB_All(void);
void    Hal_Cpu_Invalidate_DTLB_Entry(int);
void    Hal_Cpu_Lockdown_UTLB_Entry(int);

void    Hal_Cpu_Enable_Big_Endian(void);

int     Hal_Cpu_Read_PID(void);
void    Hal_Cpu_Write_PID(int pid);

void    Hal_Cpu_Wait_For_Interrupt(void);

void    Hal_Cpu_Write_TTB_Control(u_int32);
void    Hal_Cpu_Write_TTB_Base(u_int32);

u_int32 Hal_Cpu_Is_MMU_On(void);

void    Hal_Cpu_Activate_MMU(void);
void    Hal_Cpu_Deactivate_MMU(void);

void    Hal_Set_CPU_On_AMP(void);
void    Hal_Set_CPU_On_SMP(void);

void    Hal_Set_Secondary_CPU_Idle(void);
void    Sys_Enter_WFI(void);
void    Sys_Enter_BE(void);
void    Sys_Enter_LE(void);



void    Hal_Set_L1_Excl(u_int32 excl_mode);

#endif

